name = "ecolodgeloanfund"
main = "worker.ts"
compatibility_date = "2024-01-01"

[assets]
directory = "./dist"
not_found_handling = "single-page-application"

[[kv_namespaces]]
binding = "SANDOGH_KV"
id = "b788134e43904c45956d39857cf29e86"


